repos:
  - repo: local
    hooks:
      - id: pytest-on-push
        name: Run pytest on push
        entry: pytest -q
        language: python
        additional_dependencies: 
          - -rrequirements.txt
        stages: [push]
        types: [python]