default_language_version:
  python: python3

repos:
  - repo: local
    hooks:
      - id: pytest-on-pre-push
        name: Run pytest before push
        language: system          # usa seu venv atual
        entry: bash -lc 'pytest -q'
        pass_filenames: false     # não passar arquivos como args ao pytest
        stages: [pre-push]
