name: Backend Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
      REMOTE_USER: ${{ secrets.DEPLOY_USER }}
      REMOTE_PATH: ${{ secrets.DEPLOY_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts

      - name: Upload environment file (optional)
        if: ${{ secrets.ENV_FILE_PROD != '' }}
        env:
          ENV_FILE_PROD: ${{ secrets.ENV_FILE_PROD }}
        run: |
          tmp_env="$(mktemp)"
          printf '%s\n' "${ENV_FILE_PROD}" > "$tmp_env"
          scp "$tmp_env" "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}/.env"
          rm -f "$tmp_env"

      - name: Sync project to server
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude 'venv' \
            --exclude '.venv' \
            --exclude '__pycache__' \
            --exclude '.env' \
            ./ "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"

      - name: Apply remote updates
        run: |
          ssh "${REMOTE_USER}@${REMOTE_HOST}" <<'EOF'
            set -e
            cd "${REMOTE_PATH}"
            python3 -m venv .venv || true
            source .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            # Execute migrações ou scripts adicionais aqui:
            # alembic upgrade head
            sudo systemctl start postgresql.service || true
            sudo systemctl start redis-server.service || true
            sudo systemctl restart rota-backend.service
          EOF
